<a id="inicio"></a>
<br><br><br>
<div align="left">
<h1><font size=6>Pandas</font></h1>
    <h2><font color="#5E5E5E" size=5>Ejercicios III (Evaluable)</font>  </h2>
<br><br><br><br>
</div>


<div align="right">
<font color="#B51700" size=4><b>Análisis y visualización de datos</b></font><br><br>
<font  size=3>Máster Universitario en Ingeniería Informática</font><br>
<font  size=3>Máster Universitario en Big Data y Computación en la Nube</font><br>
<font size=3>Máster Universitario en Inteligencia Artificial</font><br><br>
<font color="#5E5E5E" size=3><b>Luis de la Ossa  &nbsp;&nbsp;</b></font><span style="background-color:#B51700; color:white; padding:2px 6px; font-family:Arial, sans-serif;font-weight:bold;font-size:18px;">UCLM</span>
</div>

---
#### Nombre:  ARANTZAZU OTAL ALBERRO
---

### Instrucciones

* Es **obligatorio poner el nombre** en la celda correspondiente (arriba)
* Ninguna de las celdas de código se puede eliminar
* No se permite añadir celdas (al menos, no se considerarán en la corrección)
* Cada ejercicio se puntua con 0.5 puntos
* Se penalizará con un punto menos la "suciedad" ententida como la impresión innecesaria de datos
* **Hay que entregar la libreta ejecutada**:
    * Kernel -> *Restart and Clear Output*
    * Ejecutar todas las celdas seguidas

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 1</font> 

El archivo `data/movies.csv` contiene información sobre películas estrenadas desde el año 1927. Cargarlo en un *DataFrame* denominado `df_movies` considerando que:
* El caracter separador de las columnas es `;`
* Las columnas `movie_id`, `title` y `original_language` deben ser de tipo *str*
* El índice del *DataFrame* debe ser la columna `movie_id`, que contiene el identificador de cada película

In [1]:
import pandas as pd

df_movies = pd.read_csv('./data/movies.csv', sep=";", dtype={"movie_id": str,"title": str, "original_language": str},index_col='movie_id') ### COMPLETAR

df_movies.head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine..."
tt0018455,Sunrise,"Drama,Romance",0,1636000,1927-11-04,en,7.4273,"adultery,lake,love triangle,pig,marriage crisi..."
tt0019254,The Passion of Joan of Arc,"Biography,Drama,History",0,18121,1928-04-21,fr,6.6250,"suffering,court case,judge,sentence,woman mart..."
tt0020629,All Quiet on the Western Front,"Drama,War",1448864,3270000,1930-04-29,en,6.1965,"friendship,army,based on novel or book,germany..."
tt0021749,City Lights,"Comedy,Drama,Romance",1500000,4250000,1931-02-06,en,8.1617,"blindness and impaired vision,eye operation,op..."


El archivo `data/people.csv` contiene información sobre directores y actores/actrices principales en estas peliculas. Cargarlo en un *DataFrame* denominado `df_people` considerando que:
* El caracter separador de las columnas es `;`
* Las columnas `name`, `imbdb_id` y deben ser de tipo *String*

In [2]:
df_people = pd.read_csv('./data/people.csv', dtype={"name":str, "imbdb_id": str}, sep=";")

df_people.head()

   people_id           name  popularity    imdb_id  gender
0          1   George Lucas      2.5232  nm0000184       2
1          2    Mark Hamill      3.9808  nm0000434       2
2          3  Harrison Ford      6.1804  nm0000148       2
3          4  Carrie Fisher      2.7497  nm0000402       1
4          5  Peter Cushing      2.5859  nm0001088       2

Establecer como índice del *DataFrame* la columna `people_id`. Actuar sobre el propio *DataFrame* (sin crear ninguna copia).

In [3]:
### COMPLETAR
df_people =df_people.set_index('people_id')

df_people

                            name  popularity     imdb_id  gender
people_id
1                   George Lucas      2.5232   nm0000184       2
2                    Mark Hamill      3.9808   nm0000434       2
3                  Harrison Ford      6.1804   nm0000148       2
4                  Carrie Fisher      2.7497   nm0000402       1
5                  Peter Cushing      2.5859   nm0001088       2
...                          ...         ...         ...     ...
5615231    Shannon Mahina Gorman      0.8154  nm17559412       1
6263070            Chris the Dog      0.4965         NaN       2
6390078             Carey Gibson      0.2976         NaN       0
6390079       Beverly Dollarhide      0.2584         NaN       0
6390094             Bryan Gibson      0.2975         NaN       0

[8717 rows x 4 columns]

Por último, el archivo `data/credits.csv` contiene información sobre la participación de directores y actores/actrices principales en estas películas. Cargarlo en un *DataFrame* denominado `df_credits` considerando que:
* El caracter separador de las columnas es `;`
* Las columnas `movie_id`, `rol` y deben ser de tipo *String*
* Se utiliza un índice por defecto

In [4]:
df_credits = pd.read_csv('./data/credits.csv', dtype={"movie_id":str, "rol": str}, sep=";")### COMPLETAR

df_credits.head()

   people_id   movie_id       rol
0         68  tt0017136  director
1       9076  tt0018455  director
2      11572  tt0019254  director
3       2000  tt0020629  director
4      13848  tt0021749  director

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 2</font> 

¿Cuántos valores perdidos tienen las columnas del *DataFrame* `df_movies`?

In [5]:
### COMPLETAR

df_movies.isna().sum()

title                 0
genres                1
budget                0
revenue               0
release_date          0
original_language     0
popularity            0
keywords             15
dtype: int64

Convertir la columna `release_date` a una serie de marcas de tiempo.

In [6]:
### COMPLETAR

df_movies["release_date"] = df_movies["release_date"].apply(lambda x: pd.to_datetime(x))
df_movies

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine..."
tt0018455,Sunrise,"Drama,Romance",0,1636000,1927-11-04,en,7.4273,"adultery,lake,love triangle,pig,marriage crisi..."
tt0019254,The Passion of Joan of Arc,"Biography,Drama,History",0,18121,1928-04-21,fr,6.6250,"suffering,court case,judge,sentence,woman mart..."
tt0020629,All Quiet on the Western Front,"Drama,War",1448864,3270000,1930-04-29,en,6.1965,"friendship,army,based on novel or book,germany..."
tt0021749,City Lights,"Comedy,Drama,Romance",1500000,4250000,1931-02-06,en,8.1617,"blindness and impaired vision,eye operation,op..."
...,...,...,...,...,...,...,...,...
tt9784798,Judas and the Black Messiah,"Biography,Crime,Drama",26000000,6416063,2021-02-12,en,6.5069,"chicago, illinois,assassination,black panther ..."
tt9844522,Escape Room: Tournament of Champions,"Action,Adventure,Horror",15000000,65774490,2021-07-01,en,11.8965,"sequel,no escape,escape room,death game"
tt9866072,Holidate,"Comedy,Romance",0,0,2020-10-27,en,6.3067,"new year's eve,date,holiday,single,family dinn..."
tt9893250,I Care a Lot,"Comedy,Crime,Drama",0,0,2021-02-19,en,11.3948,"psychopath,dark comedy,sociopath,guardian,soci..."
tt9900782,Kaithi,"Action,Crime,Thriller",0,522938,2019-10-24,ta,2.7814,"prisoner,police officer,one night,lokesh cinem..."

Ordenar el *DataFrame* `df_movies` por fecha de estreno (`release_date`), comenzando por la película más reciente. Operar sobre el propio *DataFrame*

In [7]:
### COMPLETAR
df_movies = df_movies.sort_values(by="release_date",ascending=False)

df_movies

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt35538033,Resident Evil,Horror,75000000,320225000,2026-09-16,en,667.2432,"outbreak,survival,decapitation,zombie,based on..."
tt11561116,The Whisper Man,"Crime,Drama,Thriller",50000000,0,2026-08-27,en,36.2161,"based on novel or book,serial killer,writer,ab..."
tt27165187,The End of Oak Street,"Action,Adventure",80000000,120363694,2026-08-12,en,177.6834,"teleportation,giant snake,time travel,wormhole..."
tt32268156,The Last House,"Action,Horror,Mystery",0,0,2026-08-06,en,24.0136,"monster,isolation,water monster,family,sea cre..."
tt22084616,Spider-Man: Brand New Day,"Action,Adventure",225000000,2512865567,2026-07-29,en,1024.5071,"mind control,new york city,hero,mutation,secre..."
...,...,...,...,...,...,...,...,...
tt0021749,City Lights,"Comedy,Drama,Romance",1500000,4250000,1931-02-06,en,8.1617,"blindness and impaired vision,eye operation,op..."
tt0020629,All Quiet on the Western Front,"Drama,War",1448864,3270000,1930-04-29,en,6.1965,"friendship,army,based on novel or book,germany..."
tt0019254,The Passion of Joan of Arc,"Biography,Drama,History",0,18121,1928-04-21,fr,6.6250,"suffering,court case,judge,sentence,woman mart..."
tt0018455,Sunrise,"Drama,Romance",0,1636000,1927-11-04,en,7.4273,"adultery,lake,love triangle,pig,marriage crisi..."
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine..."

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 3</font> 

En `df_movies`, descartar las películas anteriores a 1990.

In [8]:
df_movies = df_movies[df_movies["release_date"]>pd.to_datetime("1990-01-01")]### COMPLETAR



df_movies.sort_values(by="release_date",ascending=True).head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt0100814,Tremors,"Comedy,Horror",11000000,48572000,1990-01-19,en,12.0645,"small town,nevada,old town,stranded,rural area..."
tt0100263,La Femme Nikita,"Action,Crime,Drama",6000000,5018604,1990-02-21,fr,7.4380,"undercover agent,venice, italy,shotgun,secret ..."
tt0099810,The Hunt for Red October,"Action,Adventure,Drama",30000000,200512643,1990-03-02,en,16.1851,"based on novel or book,submarine,cold war,inte..."
tt0100405,Pretty Woman,"Comedy,Romance",14000000,463406268,1990-03-23,en,23.8324,"prostitute,sports car,capitalism,expensive res..."
tt0100758,Teenage Mutant Ninja Turtles,"Action,Adventure,Comedy",13500000,201965915,1990-03-30,en,9.8527,"new york city,martial arts,skateboarding,broth..."

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 4</font> 

Crear una columna denominada `earnings` en el *DataFrame* `df_movies`. Esta debe contener las ganancias, es decir la diferencia entre la recaudación (`revenue`) y el presupuesto (`budget`).

In [9]:
### COMPLETAR

df_movies["earnings"] = df_movies["revenue"]-df_movies["budget"]

df_movies.head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords,earnings
movie_id,,,,,,,,,
tt35538033,Resident Evil,Horror,75000000,320225000,2026-09-16,en,667.2432,"outbreak,survival,decapitation,zombie,based on...",245225000
tt11561116,The Whisper Man,"Crime,Drama,Thriller",50000000,0,2026-08-27,en,36.2161,"based on novel or book,serial killer,writer,ab...",-50000000
tt27165187,The End of Oak Street,"Action,Adventure",80000000,120363694,2026-08-12,en,177.6834,"teleportation,giant snake,time travel,wormhole...",40363694
tt32268156,The Last House,"Action,Horror,Mystery",0,0,2026-08-06,en,24.0136,"monster,isolation,water monster,family,sea cre...",0
tt22084616,Spider-Man: Brand New Day,"Action,Adventure",225000000,2512865567,2026-07-29,en,1024.5071,"mind control,new york city,hero,mutation,secre...",2287865567

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 5</font>

Mostrar las cinco películas con más ganancias.

In [10]:
### COMPLETAR

df_movies.sort_values(by="earnings",ascending=False).head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords,earnings
movie_id,,,,,,,,,
tt0499549,Avatar,"Action,Adventure,Fantasy",237000000,2923706026,2009-12-16,en,41.8923,"paraplegic,attachment to nature,culture clash,...",2686706026
tt4154796,Avengers: Endgame,"Action,Adventure,Sci-Fi",356000000,2927449455,2019-04-24,en,96.8577,"superhero,time travel,space travel,time machin...",2571449455
tt22084616,Spider-Man: Brand New Day,"Action,Adventure",225000000,2512865567,2026-07-29,en,1024.5071,"mind control,new york city,hero,mutation,secre...",2287865567
tt0120338,Titanic,"Drama,Romance",200000000,2264162353,1997-12-18,en,39.3321,"ship,soulmates,shipwreck,atlantic ocean,evacua...",2064162353
tt1630029,Avatar: The Way of Water,"Action,Adventure,Fantasy",460000000,2334484620,2022-12-14,en,40.3264,"dying and death,loss of loved one,alien life-f...",1874484620

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 6</font> 

Mostrar el número de películas en las que el beneficio sea menor o igual que cero.

In [11]:
### COMPLETAR
len(df_movies[df_movies["earnings"]<=0])

908

In [12]:
import pandas as pd

df_movies = pd.read_csv('./data/movies.csv', sep=";", dtype={"movie_id": str,"title": str, "original_language": str},index_col='movie_id') ### COMPLETAR

df_movies.head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine..."
tt0018455,Sunrise,"Drama,Romance",0,1636000,1927-11-04,en,7.4273,"adultery,lake,love triangle,pig,marriage crisi..."
tt0019254,The Passion of Joan of Arc,"Biography,Drama,History",0,18121,1928-04-21,fr,6.6250,"suffering,court case,judge,sentence,woman mart..."
tt0020629,All Quiet on the Western Front,"Drama,War",1448864,3270000,1930-04-29,en,6.1965,"friendship,army,based on novel or book,germany..."
tt0021749,City Lights,"Comedy,Drama,Romance",1500000,4250000,1931-02-06,en,8.1617,"blindness and impaired vision,eye operation,op..."

Mostrar las tres últimas películas en las que le beneficio ha sido menor o igual que cero.

In [13]:
### COMPLETAR

df_movies[(df_movies["revenue"]-df_movies["budget"])<=0].head(3).sort_values(by="release_date",ascending=False)

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt0023969,Duck Soup,"Comedy,Musical",0,0,1933-11-12,en,3.6768,"ambassador,dictator,widow,spy,siege,musical,le..."
tt0022913,Freaks,"Drama,Horror",310607,0,1932-01-01,en,4.9878,"infidelity,dwarf,attempted murder,clown,beauty..."
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine..."


En algunas de estas peliculas da la sensación de que faltan los datos de presupuestos o ganancias. Mostrar ahora las tres últimas películas con pérdidas para las que las ganancias (`revenue`) han sido mayores que cero.

In [14]:
### COMPLETAR

df_movies[(df_movies["revenue"]-df_movies["budget"]<=0) & (df_movies["revenue"]>0)].head(3).sort_values(by="release_date",ascending=False)

,title,genres,budget,revenue,release_date,original_language,popularity,keywords
movie_id,,,,,,,,
tt0044741,Ikiru,Drama,85000,55240,1952-10-09,ja,13.0873,"dying and death,japan,bureaucracy,age differen..."
tt0042876,Rashomon,"Crime,Drama,Mystery",250000,117668,1950-08-26,ja,8.2499,"dying and death,japan,samurai,rape,court case,..."
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine..."

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 7</font> 

Calcular el número de películas en cada lenguaje original (`original_language`) y su presupuesto medio. Mostrar los cinco lenguajes con mayor presupuesto medio.

In [15]:
### COMPLETAR
presupuesto = df_movies.groupby("original_language")["budget"].mean()
df = pd.DataFrame(presupuesto)
df.sort_values(by="budget", ascending=False).head()

                         budget
original_language
en                 4.628440e+07
zh                 3.562014e+07
te                 3.418116e+07
fr                 1.070914e+07
nl                 1.050000e+07

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 8</font>  

Mostrar el número de películas estrenadas cada año. Ordenar de forma ascendente por año.

In [16]:
### COMPLETAR
p = df_movies.groupby(pd.to_datetime(df_movies['release_date']).dt.year)["title"].count().sort_index(ascending=True)
df = pd.DataFrame(p)
df

              title
release_date
1927              2
1928              1
1930              1
1931              4
1932              1
...             ...
2022            118
2023            118
2024            101
2025             92
2026             47

[98 rows x 1 columns]

Mostrar la popularidad (`popularity`) media de las películas estrenadas cada año. Ordenar de forma ascendente por año.

In [17]:
### COMPLETAR
p = df_movies.groupby(pd.to_datetime(df_movies['release_date']).dt.year)["popularity"].mean().sort_index(ascending=True)
df = pd.DataFrame(p)
df

              popularity
release_date
1927            7.359350
1928            6.625000
1930            6.196500
1931            9.122200
1932            4.987800
...                  ...
2022           15.058531
2023           16.855870
2024           18.881769
2025           25.114701
2026           87.457409

[98 rows x 1 columns]

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 9</font>  

El archivo `data/title.ratings.tsv.gz` contiene datos sobre las votaciones del público en IMDb. Leer el archivo y cargarlo en un *DataFrame* denominado `df_ratings`. Fijar como índice la primera columna. 

Las columnas de este archivo están separadas por tabulaciones (caracter `"\t"`), y los valores perdidos se representan con `'\N'`. La función `pd.read_csv()` de _Pandas_ también leer directamente archivos comprimidos directamente. Para ello, en este caso, hay que pasarle el parámetro `compression='gzip'` (la lectura requiere varios segundos).

In [18]:
### COMPLETAR

df_ratings = pd.read_csv('./data/title.ratings.tsv.gz', sep='\t', index_col=0, compression='gzip').fillna('\n')

df_ratings.head()

           averageRating  numVotes
tconst
tt0000001            5.7      2233
tt0000002            5.4       327
tt0000003            6.4      2393
tt0000004            5.0       203
tt0000005            6.2      3099

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 10</font>  

Añadir la información de `df_ratings` (las columnas `averageRating` y `numVotes`) a `df_movies`. Asegurarse de que no se añaden filas nuevas, y que se mantiene una relacion uno a uno.

In [19]:
### COMPLETAR

df_movies["averageRating"]=df_ratings["averageRating"]
df_movies["numVotes"]=df_ratings["numVotes"]
df_movies

,title,genres,budget,revenue,release_date,original_language,popularity,keywords,averageRating,numVotes
movie_id,,,,,,,,,,
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine...",8.2,203553
tt0018455,Sunrise,"Drama,Romance",0,1636000,1927-11-04,en,7.4273,"adultery,lake,love triangle,pig,marriage crisi...",8.1,57223
tt0019254,The Passion of Joan of Arc,"Biography,Drama,History",0,18121,1928-04-21,fr,6.6250,"suffering,court case,judge,sentence,woman mart...",8.1,69491
tt0020629,All Quiet on the Western Front,"Drama,War",1448864,3270000,1930-04-29,en,6.1965,"friendship,army,based on novel or book,germany...",8.1,72927
tt0021749,City Lights,"Comedy,Drama,Romance",1500000,4250000,1931-02-06,en,8.1617,"blindness and impaired vision,eye operation,op...",8.5,218699
...,...,...,...,...,...,...,...,...,...,...
tt9784798,Judas and the Black Messiah,"Biography,Crime,Drama",26000000,6416063,2021-02-12,en,6.5069,"chicago, illinois,assassination,black panther ...",7.4,116402
tt9844522,Escape Room: Tournament of Champions,"Action,Adventure,Horror",15000000,65774490,2021-07-01,en,11.8965,"sequel,no escape,escape room,death game",5.8,70044
tt9866072,Holidate,"Comedy,Romance",0,0,2020-10-27,en,6.3067,"new year's eve,date,holiday,single,family dinn...",6.2,89098
tt9893250,I Care a Lot,"Comedy,Crime,Drama",0,0,2021-02-19,en,11.3948,"psychopath,dark comedy,sociopath,guardian,soci...",6.4,160968
tt9900782,Kaithi,"Action,Crime,Thriller",0,522938,2019-10-24,ta,2.7814,"prisoner,police officer,one night,lokesh cinem...",8.4,52980

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 11</font>

Renombrar las columnas `averageRating` y `numVotes` a `avg_rating` y `num_votes` respectivamente. Hacerlo sobre el propio `DataFrame`.

In [20]:
### COMPLETAR
df_movies = df_movies.rename(columns={'averageRating':'avg_rating','numVotes':'num_votes'})
df_movies

,title,genres,budget,revenue,release_date,original_language,popularity,keywords,avg_rating,num_votes
movie_id,,,,,,,,,,
tt0017136,Metropolis,"Drama,Sci-Fi",5300000,1350322,1927-01-10,de,7.2914,"future,metropolis,class society,man vs machine...",8.2,203553
tt0018455,Sunrise,"Drama,Romance",0,1636000,1927-11-04,en,7.4273,"adultery,lake,love triangle,pig,marriage crisi...",8.1,57223
tt0019254,The Passion of Joan of Arc,"Biography,Drama,History",0,18121,1928-04-21,fr,6.6250,"suffering,court case,judge,sentence,woman mart...",8.1,69491
tt0020629,All Quiet on the Western Front,"Drama,War",1448864,3270000,1930-04-29,en,6.1965,"friendship,army,based on novel or book,germany...",8.1,72927
tt0021749,City Lights,"Comedy,Drama,Romance",1500000,4250000,1931-02-06,en,8.1617,"blindness and impaired vision,eye operation,op...",8.5,218699
...,...,...,...,...,...,...,...,...,...,...
tt9784798,Judas and the Black Messiah,"Biography,Crime,Drama",26000000,6416063,2021-02-12,en,6.5069,"chicago, illinois,assassination,black panther ...",7.4,116402
tt9844522,Escape Room: Tournament of Champions,"Action,Adventure,Horror",15000000,65774490,2021-07-01,en,11.8965,"sequel,no escape,escape room,death game",5.8,70044
tt9866072,Holidate,"Comedy,Romance",0,0,2020-10-27,en,6.3067,"new year's eve,date,holiday,single,family dinn...",6.2,89098
tt9893250,I Care a Lot,"Comedy,Crime,Drama",0,0,2021-02-19,en,11.3948,"psychopath,dark comedy,sociopath,guardian,soci...",6.4,160968
tt9900782,Kaithi,"Action,Crime,Thriller",0,522938,2019-10-24,ta,2.7814,"prisoner,police officer,one night,lokesh cinem...",8.4,52980

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 8</font>  

Mostrar el número de películas estrenadas cada año. Ordenar de forma ascendente por año.

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 12</font>  

Comprobar si hay alguna película para la que no se haya especificado el número de votos.

In [21]:
### COMPLETAR
df_movies[(df_movies["num_votes"]<=0) | (df_movies["num_votes"].isna() )]

Empty DataFrame
Columns: [title, genres, budget, revenue, release_date, original_language, popularity, keywords, avg_rating, num_votes]
Index: []

Comprobar si hay alguna película para la que el número de votos sea cero.

In [22]:
### COMPLETAR

df_movies[df_movies["num_votes"]==0]

Empty DataFrame
Columns: [title, genres, budget, revenue, release_date, original_language, popularity, keywords, avg_rating, num_votes]
Index: []

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 13</font> 

Ordenar las películas por número de votos (`num_votes`), y mostrar las cinco primeras.

In [23]:
### COMPLETAR
df_movies.sort_values(by='num_votes',ascending=False).head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords,avg_rating,num_votes
movie_id,,,,,,,,,,
tt0111161,The Shawshank Redemption,Drama,25000000,28341469,1994-09-23,en,56.2948,"prison,friendship,police brutality,corruption,...",9.3,3251264
tt0468569,The Dark Knight,"Crime,Thriller",185000000,1008480529,2008-07-16,en,58.4739,"sadism,chaos,secret identity,crime fighter,sup...",9.1,3238161
tt1375666,Inception,"Adventure,Sci-Fi,Thriller",160000000,839030630,2010-07-15,en,50.9469,"mission,dreams,kidnapping,spy,allegory,intelle...",8.8,2878617
tt0137523,Fight Club,"Crime,Drama,Thriller",63000000,100853753,1999-10-15,en,41.7618,"dual identity,rage and hate,based on novel or ...",8.8,2671562
tt0816692,Interstellar,"Adventure,Sci-Fi",165000000,746606706,2014-11-04,en,64.8050,"spacecraft,race against time,artificial intell...",8.7,2619532

Ordenar las películas por valoración media (`avg_rating`) y mostrar las cinco primeras.

In [24]:
### COMPLETAR
df_movies.sort_values(by='avg_rating',ascending=False).head()

,title,genres,budget,revenue,release_date,original_language,popularity,keywords,avg_rating,num_votes
movie_id,,,,,,,,,,
tt0111161,The Shawshank Redemption,Drama,25000000,28341469,1994-09-23,en,56.2948,"prison,friendship,police brutality,corruption,...",9.3,3251264
tt0068646,The Godfather,"Crime,Drama",6000000,245066411,1972-03-14,en,59.9212,"based on novel or book,loss of loved one,love ...",9.2,2263991
tt0468569,The Dark Knight,"Crime,Thriller",185000000,1008480529,2008-07-16,en,58.4739,"sadism,chaos,secret identity,crime fighter,sup...",9.1,3238161
tt0050083,12 Angry Men,"Crime,Drama",397751,4360000,1957-04-10,en,38.9130,"death penalty,anonymity,court case,judge,juror...",9.0,1007285
tt0167260,The Lord of the Rings: The Return of the King,"Adventure,Drama,Fantasy",94000000,1118888979,2003-12-17,en,42.3406,"army,based on novel or book,elves,dwarf,magic,...",9.0,2200068

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 14</font>  

La columna `genres` contiene un *string* con los géneros en los que se puede catalogar cada película separados por comas. Convertir cada una de esas cadenas a una lista en la que cada elemento corresponda a un género.

In [25]:
### COMPLETAR

df_movies['genres'] = df_movies['genres'].fillna('').str.split(',')

df_movies['genres']

movie_id
tt0017136                [Drama, Sci-Fi]
tt0018455               [Drama, Romance]
tt0019254    [Biography, Drama, History]
tt0020629                   [Drama, War]
tt0021749       [Comedy, Drama, Romance]
                        ...
tt9784798      [Biography, Crime, Drama]
tt9844522    [Action, Adventure, Horror]
tt9866072              [Comedy, Romance]
tt9893250         [Comedy, Crime, Drama]
tt9900782      [Action, Crime, Thriller]
Name: genres, Length: 4663, dtype: object

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 14</font>  

La columna `genres` contiene un *string* con los géneros en los que se puede catalogar cada película separados por comas. Convertir cada una de esas cadenas a una lista en la que cada elemento corresponda a un género.

Contar el número de veces que aparece cada género.

In [26]:
### COMPLETAR
df_movies['genres'].explode().value_counts()

genres
Drama          2356
Comedy         1584
Action         1421
Adventure      1156
Crime           965
Thriller        860
Romance         626
Horror          596
Mystery         576
Sci-Fi          450
Fantasy         422
Biography       339
Animation       292
Family          224
History         128
Music           105
Sport           101
War              87
Musical          50
Western          35
Documentary      35
Film-Noir        12
News              1
                  1
Name: count, dtype: int64

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 15</font>  

Mostrar el presupuesto medio de las películas de cada género (`explode` + `groupby`). Mostrar de forma descendente.

In [27]:
### COMPLETAR
df_movies['genres'] 
x = df_movies.explode('genres').groupby('genres')["budget"].mean()
dat = pd.DataFrame(x)
dat.sort_values(by='budget',ascending=False)

                   budget
genres
Adventure    8.574480e+07
Animation    7.918530e+07
Sci-Fi       7.177409e+07
Action       7.146521e+07
Fantasy      6.553024e+07
Family       6.414860e+07
Comedy       3.979387e+07
History      3.942547e+07
Thriller     3.544675e+07
Sport        3.347078e+07
Crime        3.144305e+07
Musical      3.105089e+07
Biography    2.826689e+07
Drama        2.818416e+07
Romance      2.620359e+07
War          2.417995e+07
Mystery      2.370860e+07
Music        1.980992e+07
Horror       1.960788e+07
Western      1.771747e+07
Documentary  3.787571e+06
News         1.000000e+06
Film-Noir    8.477718e+05
             0.000000e+00

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 16</font>  

En el *DataFrame* `df_people`, convertir la columna `gender` a categórica, utilizando las etiquetas especificadas en el diccionario `genres`.

In [28]:
genres = {
    0: 'Not specified',
    1: 'Female',
    2: 'Male',
    3: 'Non-binary'
}

cat = df_people['gender'].map(genres)
df_people['gender'] = pd.Categorical(cat, categories=genres.values(), ordered=False)
df_people['gender']

people_id
1                   Male
2                   Male
3                   Male
4                 Female
5                   Male
               ...
5615231           Female
6263070             Male
6390078    Not specified
6390079    Not specified
6390094    Not specified
Name: gender, Length: 8717, dtype: category
Categories (4, str): ['Not specified', 'Female', 'Male', 'Non-binary']

Mostrar el número de veces que aparece cada género.

In [29]:
### COMPLETAR

df_people.groupby("gender")["gender"].count()

gender
Not specified      99
Female           2776
Male             5822
Non-binary         20
Name: gender, dtype: int64

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 17</font> 
En el *DataFrame* `df_credits`, dejar solamente aquellas entradas correspondientes a las películas que contiene `df_movies`.

In [30]:
df_credits=df_credits[df_credits["movie_id"].isin(df_movies.index)] ### COMPLETAR
df_credits

       people_id   movie_id       rol
0             68  tt0017136  director
1           9076  tt0018455  director
2          11572  tt0019254  director
3           2000  tt0020629  director
4          13848  tt0021749  director
...          ...        ...       ...
23666       1902  tt9893250      cast
23667     123066  tt9900782      cast
23668     587752  tt9900782      cast
23669    2483439  tt9900782      cast
23670    1103227  tt9900782      cast

[23671 rows x 3 columns]

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 18</font> 
Crear una *Series* denominada `directors`que cuyo índice sea `people_id` y que contenga el número de películas dirigidas por cada persona.

In [63]:
df_directors = df_credits[df_credits["rol"] == "director"]
directors = df_directors.groupby("people_id")["movie_id"].count()
directors.name = "Numero de peliculas dirigidas" 
directors.index.name = "Director id"
directors.sort_values(ascending=False)

Director id
488        31
190        25
578        25
1032       21
6159       21
           ..
4487238     1
4487237     1
4347786     1
3999942     1
3820182     1
Name: Numero de peliculas dirigidas, Length: 1955, dtype: int64

Crear una *Series* denominada `cast`que cuyo índice sea `people_id` y que contenga el número de películas en las que ha actuado cada persona.

In [64]:
df_cast = df_credits[df_credits["rol"] == "cast"]
cast = df_cast.groupby("people_id")["movie_id"].count()
cast.name = "Numero de peliculas en las que han actuado" 
cast.index.name = "Cast id"
cast.sort_values(ascending=False)

Cast id
380     58
31      47
2231    44
2963    43
62      42
        ..
23       1
22       1
18       1
12       1
10       1
Name: Numero de peliculas en las que han actuado, Length: 6929, dtype: int64

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 19</font> 

En el *DataFrame* `df_people`, crear una columna denominada `directs` que contenga la serie `directors`, y otra denominada `acts` que contengales la serie `cast`.

In [66]:
### COMPLETAR

df_people["directs"] = directors
df_people["acts"] = cast

df_people

,name,popularity,imdb_id,gender,directs,acts
people_id,,,,,,
1,George Lucas,2.5232,nm0000184,Male,6.0,NaN
2,Mark Hamill,3.9808,nm0000434,Male,NaN,7.0
3,Harrison Ford,6.1804,nm0000148,Male,NaN,31.0
4,Carrie Fisher,2.7497,nm0000402,Female,NaN,7.0
5,Peter Cushing,2.5859,nm0001088,Male,NaN,2.0
...,...,...,...,...,...,...
5615231,Shannon Mahina Gorman,0.8154,nm17559412,Female,NaN,1.0
6263070,Chris the Dog,0.4965,NaN,Male,NaN,1.0
6390078,Carey Gibson,0.2976,NaN,Not specified,NaN,1.0
6390079,Beverly Dollarhide,0.2584,NaN,Not specified,NaN,1.0
6390094,Bryan Gibson,0.2975,NaN,Not specified,NaN,1.0

Mostrar los diez directores que más películas han dirigido

In [67]:
### COMPLETAR
df_people.sort_values(by='directs',ascending=False).head(10)

                        name  popularity    imdb_id gender  directs  acts
people_id
488         Steven Spielberg      6.5438  nm0000229   Male     31.0   NaN
190           Clint Eastwood      8.1224  nm0000142   Male     25.0  26.0
578             Ridley Scott      4.0802  nm0000631   Male     25.0   NaN
1032         Martin Scorsese      7.0178  nm0000217   Male     21.0   NaN
6159              Ron Howard      3.0282  nm0000165   Male     21.0   1.0
510               Tim Burton      4.1515  nm0000318   Male     20.0   NaN
1243             Woody Allen      2.8634  nm0000095   Male     19.0   9.0
1223               Joel Coen      2.3455  nm0001054   Male     19.0   NaN
1884       Steven Soderbergh      2.2185  nm0001752   Male     18.0   NaN
2636        Alfred Hitchcock      3.0284  nm0000033   Male     18.0   NaN

Mostrar los diez actores/actrices que han participado en más películas.

In [68]:
### COMPLETAR
df_people.sort_values(by='acts',ascending=False).head(10)

                        name  popularity    imdb_id gender  directs  acts
people_id
380           Robert De Niro      8.2058  nm0000134   Male      2.0  58.0
31                 Tom Hanks     13.0210  nm0000158   Male      2.0  47.0
2231       Samuel L. Jackson      7.1660  nm0000168   Male      NaN  44.0
2963            Nicolas Cage      9.8246  nm0000115   Male      NaN  43.0
62              Bruce Willis      8.1796  nm0000246   Male      NaN  42.0
1892              Matt Damon     10.5561  nm0000354   Male      NaN  42.0
500               Tom Cruise     12.2495  nm0000129   Male      NaN  39.0
287                Brad Pitt     12.3468  nm0000093   Male      NaN  39.0
13240          Mark Wahlberg      6.8076  nm0000242   Male      NaN  39.0
19292           Adam Sandler      4.5053  nm0001191   Male      NaN  39.0

### <font size=3> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Ejercicio 20</font> 

¿Qué actores han participado en las peliculas que ha dirigido Clint Eastwood? Devolver el resutado ordenado por popularidad.

In [85]:
### COMPLETAR
people = df_people[df_people['name']=='Clint Eastwood']
pelis_de_clint = df_credits[(df_credits["people_id"].isin(people.index))&(df_credits["rol"]=='director')]["movie_id"]
cast = df_credits[(df_credits["movie_id"].isin(pelis_de_clint))&(df_credits["rol"]=='cast')]["people_id"]
personas_en_pelis_de_clint = df_people[df_people.index.isin(cast)]
personas_en_pelis_de_clint.sort_values(by='popularity',ascending=False)

                        name  popularity    imdb_id  gender  directs  acts
people_id
31                 Tom Hanks     13.0210  nm0000158    Male      2.0  47.0
1892              Matt Damon     10.5561  nm0000354    Male      NaN  42.0
192           Morgan Freeman      9.5503  nm0000151    Male      NaN  34.0
11701         Angelina Jolie      9.5256  nm0001401  Female      1.0  24.0
6193       Leonardo DiCaprio      8.6854  nm0000138    Male      NaN  26.0
...                      ...         ...        ...     ...      ...   ...
55192            Verna Bloom      0.9862  nm0089244  Female      NaN   2.0
74309               Bee Vang      0.8046  nm3057402    Male      NaN   1.0
63136       Patrick Mofokeng      0.7634  nm0595680    Male      NaN   1.0
66670       Chief Dan George      0.5908  nm0313381    Male      NaN   1.0
1530518           Cole Konis      0.5365  nm6518675    Male      NaN   1.0

[80 rows x 6 columns]

<br>
<div align="right">
<a href="#inicio"><font size=5 color="#B51700"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></font></a>
</div>

---

<div align="right">
<font size=5 color="#B51700"><i class="fa fa-coffee" aria-hidden="true"></i></font>
</div>